EMCC = emcc
EM_CACHE ?= $(CURDIR)/../../build/emscripten-cache
WASM_BUILD_DIR ?= build/wasm

WASM_CFLAGS = \
	-O2 \
	-I. \
	-DMAELYS_WASM=1

ENGINE_SRCS = \
	src/core/maelys_datalog_audit.c \
	src/core/maelys_datalog_diagnostic.c \
	src/core/maelys_datalog_domain_registry.c \
	src/core/maelys_datalog_edb.c \
	src/core/maelys_datalog_lexer.c \
	src/core/maelys_datalog_parser.c \
	src/core/maelys_datalog_policy.c \
	src/core/maelys_datalog_predicate_registry.c \
	src/core/maelys_datalog_symbol_table.c \
	src/manifest/maelys_datalog_manifest_buffer.c

COMMON_SRCS = \
	common/maelys_sha256.c \
	common/maelys_utf8.c \
	vendor/yyjson/yyjson.c

WASM_SRCS = $(ENGINE_SRCS) $(COMMON_SRCS)
EXAMPLES_SRCS = examples/domains/maelys_datalog_example_domains.c
WASM_EXAMPLES_SRCS = $(WASM_SRCS) $(EXAMPLES_SRCS)
WASM_BUILDER_SRC = src/wasm/maelys_datalog_wasm.c
WASM_DYNAMIC_SRCS = $(WASM_SRCS) $(WASM_BUILDER_SRC)

WASM_EXPORTS = \
	'_maelys_datalog_manifest_load_from_text', \
	'_maelys_datalog_policy_set_clear', \
	'_maelys_datalog_solve_once', \
	'_maelys_datalog_solve_result_free', \
	'_maelys_datalog_query_solved_ground_fact', \
	'_maelys_datalog_diag_code_name', \
	'_malloc', \
	'_free'

WASM_LDFLAGS = \
	-s "EXPORTED_FUNCTIONS=[$(WASM_EXPORTS)]" \
	-s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','stringToUTF8','lengthBytesUTF8','getValue']" \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME="MaelysDatalog"

WASM_EXAMPLES_EXPORTS = \
	$(WASM_EXPORTS), \
	'_maelys_datalog_example_domains_install'

WASM_EXAMPLES_LDFLAGS = \
	-s "EXPORTED_FUNCTIONS=[$(WASM_EXAMPLES_EXPORTS)]" \
	-s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','stringToUTF8','lengthBytesUTF8','getValue']" \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME="MaelysDatalogExamples"

WASM_DYNAMIC_EXPORTS = \
	$(WASM_EXPORTS), \
	'_maelys_datalog_load_policy_inline', \
	'_maelys_datalog_wasm_domain_begin', \
	'_maelys_datalog_wasm_domain_add_predicate', \
	'_maelys_datalog_wasm_domain_commit', \
	'_maelys_datalog_wasm_domain_abort', \
	'_maelys_datalog_wasm_edb_begin', \
	'_maelys_datalog_wasm_edb_intern_runtime_symbol', \
	'_maelys_datalog_wasm_edb_add_symbol_id_fact', \
	'_maelys_datalog_wasm_edb_add_symbol_ids_fact', \
	'_maelys_datalog_wasm_edb_add_symbol_id_facts', \
	'_maelys_datalog_wasm_edb_add_symbol_ids_facts', \
	'_maelys_datalog_wasm_edb_add_runtime_symbol_facts', \
	'_maelys_datalog_wasm_edb_add_runtime_symbol_pair_facts', \
	'_maelys_datalog_wasm_edb_add_symbol', \
	'_maelys_datalog_wasm_edb_add_symbol2', \
	'_maelys_datalog_wasm_solve', \
	'_maelys_datalog_wasm_query_symbol', \
	'_maelys_datalog_wasm_query_symbol2', \
	'_maelys_datalog_wasm_solve_result_free', \
	'_maelys_datalog_wasm_load_policy', \
	'_maelys_datalog_wasm_ruleset_ptr', \
	'_maelys_datalog_wasm_last_diag_message', \
	'_maelys_datalog_wasm_last_diag_code'

WASM_DYNAMIC_LDFLAGS = \
	-s "EXPORTED_FUNCTIONS=[$(WASM_DYNAMIC_EXPORTS)]" \
	-s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','stringToUTF8','lengthBytesUTF8','getValue','HEAP32']" \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME="MaelysDatalogDynamic"

$(WASM_BUILD_DIR)/maelys_datalog.js: $(WASM_SRCS)
	@mkdir -p $(EM_CACHE) $(WASM_BUILD_DIR)
	EM_CACHE=$(EM_CACHE) $(EMCC) $(WASM_CFLAGS) $(WASM_SRCS) $(WASM_LDFLAGS) -o $@

$(WASM_BUILD_DIR)/maelys_datalog.wasm: $(WASM_BUILD_DIR)/maelys_datalog.js

$(WASM_BUILD_DIR)/maelys_datalog_examples.js: $(WASM_EXAMPLES_SRCS)
	@mkdir -p $(EM_CACHE) $(WASM_BUILD_DIR)
	EM_CACHE=$(EM_CACHE) $(EMCC) $(WASM_CFLAGS) $(WASM_EXAMPLES_SRCS) $(WASM_EXAMPLES_LDFLAGS) -o $@

$(WASM_BUILD_DIR)/maelys_datalog_examples.wasm: $(WASM_BUILD_DIR)/maelys_datalog_examples.js

$(WASM_BUILD_DIR)/maelys_datalog_dynamic.js: $(WASM_DYNAMIC_SRCS)
	@mkdir -p $(EM_CACHE) $(WASM_BUILD_DIR)
	EM_CACHE=$(EM_CACHE) $(EMCC) $(WASM_CFLAGS) $(WASM_DYNAMIC_SRCS) $(WASM_DYNAMIC_LDFLAGS) -o $@

$(WASM_BUILD_DIR)/maelys_datalog_dynamic.wasm: $(WASM_BUILD_DIR)/maelys_datalog_dynamic.js

# Convenience aliases
maelys_datalog.js:         $(WASM_BUILD_DIR)/maelys_datalog.js
maelys_datalog_examples.js: $(WASM_BUILD_DIR)/maelys_datalog_examples.js
maelys_datalog_dynamic.js: $(WASM_BUILD_DIR)/maelys_datalog_dynamic.js

clean:
	rm -rf $(EM_CACHE)
	rm -rf $(WASM_BUILD_DIR)
	rm -f *.o src/core/*.o src/manifest/*.o src/wasm/*.o common/*.o vendor/yyjson/*.o examples/domains/*.o
