# The shipped Wasm adapter is an isolated consumer of the installed public SDK.
# The old native-object core/examples targets are intentionally removed.
WASM_PROFILE ?= small
ifeq ($(WASM_PROFILE),large)
WASM_BUILD_DIR ?= build/wasm-large
else
WASM_BUILD_DIR ?= build/wasm
endif
EM_CACHE ?= $(CURDIR)/build/emscripten-cache
.PHONY: maelys_datalog_dynamic.js maelys_datalog_dynamic_large.js clean
maelys_datalog_dynamic.js:
	EM_CACHE="$(EM_CACHE)" bash tools/build_wasm_binding.sh "$(WASM_PROFILE)" "$(WASM_BUILD_DIR)"
maelys_datalog_dynamic_large.js:
	$(MAKE) -f Makefile.wasm maelys_datalog_dynamic.js WASM_PROFILE=large WASM_BUILD_DIR=build/wasm-large
clean:
	rm -rf "$(WASM_BUILD_DIR)" build/wasm-sdk-small build/wasm-sdk-large
