/* SPDX-License-Identifier: MPL-2.0 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { create, profile, wasmURL, MaelysPlayground } from './helpers.mjs';
const pg=await create(), limits=pg.buildLimits();
assert.equal(limits.maxArity,4);
assert.equal(limits.maxFactsPerPred,profile==='large'?256:64);
assert.equal(limits.maxEdbFacts,profile==='large'?2048:1024);
assert.equal(limits.maxStringBytes,1024);
assert.ok(limits.inputEdbTextBytes>=limits.stringPoolBytes);
assert.equal(Object.keys(limits).length,12);
pg.close();
const module=await WebAssembly.compile(fs.readFileSync(wasmURL));
const exports=WebAssembly.Module.exports(module).map(x=>x.name);
const expected=JSON.parse(fs.readFileSync(new URL('../../bindings/wasm/exports.json',import.meta.url),'utf8')).map(x=>x.slice(1));
for(const name of expected) assert.ok(exports.includes(name),`Missing export ${name}`);
for(const name of exports) if(name.includes('maelys_datalog')) assert.ok(expected.includes(name),`Undeclared engine export ${name}`);
assert.ok(!exports.some(x=>x.includes('ruleset_ptr')));
for(const version of [0,2]) assert.throws(()=>new MaelysPlayground({ccall:()=>version}),/transport/);
console.log(`PASS: installed SDK ${profile}, 12 limits and ${expected.length} declared exports`);
