"""Python binding compiled only against the opaque public C facade."""

from .engine import (
    Capability,
    Diagnostic,
    Edb,
    Engine,
    ExplanationKind,
    Limits,
    MaelysDatalogError,
    Predicate,
    PRED_EDB,
    PRED_IDB,
    PRED_POLICY_FACT,
    PRED_QUERY,
    Ruleset,
    ResultTerm,
    Session,
    SolveResult,
    Status,
)

__all__ = [
    "Capability",
    "Diagnostic",
    "Edb",
    "Engine",
    "ExplanationKind",
    "Limits",
    "MaelysDatalogError",
    "Predicate",
    "PRED_EDB",
    "PRED_IDB",
    "PRED_POLICY_FACT",
    "PRED_QUERY",
    "Ruleset",
    "ResultTerm",
    "Session",
    "SolveResult",
    "Status",
]
