/* SPDX-License-Identifier: MPL-2.0 */
/* Benchmark-only source adapters. The same harness compiles against releases
 * before and after the application type cleanup; no engine code is adapted. */
#ifndef MAELYS_BENCH_TYPES_COMPAT_H
#define MAELYS_BENCH_TYPES_COMPAT_H
#include "include/maelys_datalog.h"
#include "maelys/datalog_backend.h"
#ifdef MAELYS_DATALOG_APPLICATION_TYPES_VERSION
typedef maelys_datalog_internal_fact_t maelys_bench_native_fact_t;
typedef maelys_datalog_internal_term_t maelys_bench_native_term_t;
typedef maelys_datalog_internal_term_kind_t maelys_bench_native_term_kind_t;
typedef maelys_datalog_internal_edb_t maelys_bench_native_edb_t;
typedef maelys_datalog_internal_ruleset_t maelys_bench_native_ruleset_t;
typedef maelys_datalog_internal_policy_set_t maelys_bench_native_policy_set_t;
typedef maelys_datalog_internal_prepared_session_t maelys_bench_native_prepared_session_t;
typedef maelys_datalog_internal_solve_result_t maelys_bench_native_solve_result_t;
typedef maelys_datalog_internal_diagnostic_t maelys_bench_native_diagnostic_t;
typedef maelys_datalog_internal_solve_diagnostic_t maelys_bench_native_solve_diagnostic_t;
typedef maelys_datalog_value_t maelys_bench_value_t;
typedef maelys_datalog_fact_t maelys_bench_fact_t;
typedef maelys_datalog_predicate_t maelys_bench_predicate_t;
typedef maelys_datalog_domain_t maelys_bench_domain_t;
typedef maelys_datalog_term_view_t maelys_bench_term_view_t;
typedef maelys_datalog_fact_view_t maelys_bench_fact_view_t;
#else
typedef maelys_datalog_fact_t maelys_bench_native_fact_t;
typedef maelys_datalog_term_t maelys_bench_native_term_t;
typedef maelys_datalog_term_kind_t maelys_bench_native_term_kind_t;
typedef maelys_datalog_edb_t maelys_bench_native_edb_t;
typedef maelys_datalog_ruleset_t maelys_bench_native_ruleset_t;
typedef maelys_datalog_policy_set_t maelys_bench_native_policy_set_t;
typedef maelys_datalog_prepared_session_t maelys_bench_native_prepared_session_t;
typedef maelys_datalog_solve_result_t maelys_bench_native_solve_result_t;
typedef maelys_datalog_diagnostic_t maelys_bench_native_diagnostic_t;
typedef maelys_datalog_solve_diagnostic_t maelys_bench_native_solve_diagnostic_t;
typedef maelys_datalog_public_value_t maelys_bench_value_t;
typedef maelys_datalog_public_fact_t maelys_bench_fact_t;
typedef maelys_datalog_public_predicate_t maelys_bench_predicate_t;
typedef maelys_datalog_public_domain_t maelys_bench_domain_t;
typedef maelys_datalog_public_term_view_t maelys_bench_term_view_t;
typedef maelys_datalog_public_fact_view_t maelys_bench_fact_view_t;
#endif
#endif
