#pragma once
#ifndef MAELYS_COMMON_ERRORS_H
#define MAELYS_COMMON_ERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    MAELYS_OK = 0,

    MAELYS_ERR_INVALID_ARGUMENT = -1,
    MAELYS_ERR_INVALID_FIELD = -2,
    MAELYS_ERR_NOT_FOUND = -3,
    MAELYS_ERR_NOT_IMPLEMENTED = -4,
    MAELYS_ERR_UNSUPPORTED = -5,
    MAELYS_ERR_TIMEOUT = -6,
    MAELYS_ERR_IO = -7,
    MAELYS_ERR_INTERNAL = -8,
    MAELYS_ERR_UNAUTHORIZED = -9,
    MAELYS_ERR_FORBIDDEN = -10,
    MAELYS_ERR_RATE_LIMITED = -11,
    MAELYS_ERR_PAYLOAD_TOO_LARGE = -12,
    MAELYS_ERR_INVALID_STATE = -13,

    MAELYS_ERR_PROVIDER_MISSING = -100,
    MAELYS_ERR_PROVIDER_UNKNOWN = -101,
    MAELYS_ERR_PROVIDER_BINARY_NOT_FOUND = -102,
    MAELYS_ERR_PROVIDER_BINARY_NOT_EXECUTABLE = -103,
    MAELYS_ERR_PROVIDER_BACKEND_UNAVAILABLE = -104,

    MAELYS_ERR_AGENT_NOT_FOUND = -200,
    MAELYS_ERR_AGENT_NOT_RUNNING = -201,
    MAELYS_ERR_AGENT_QUEUE_EMPTY = -202,
    MAELYS_ERR_AGENT_SESSION_DEAD = -203,
    MAELYS_ERR_AGENT_BACKEND_UNSUPPORTED = -204,
    MAELYS_ERR_AGENT_BUSY = -205,

    MAELYS_ERR_WORKFLOW_NOT_FOUND = -300,
    MAELYS_ERR_WORKFLOW_INVALID = -301,
    MAELYS_ERR_WORKFLOW_CYCLE = -302,
    MAELYS_ERR_WORKFLOW_UNKNOWN_NODE = -303,
    MAELYS_ERR_WORKFLOW_INVALID_ORDER = -304,
    MAELYS_ERR_WORKFLOW_INVALID_TRANSFER = -305,

    MAELYS_ERR_MEMORY_NOT_FOUND = -400,
    MAELYS_ERR_MEMORY_WRITE_FAILED = -401,
    MAELYS_ERR_MEMORY_READ_FAILED = -402,

    MAELYS_ERR_PLATFORM_LOCK = -500,
    MAELYS_ERR_PLATFORM_SIGACTION = -501,
    MAELYS_ERR_PLATFORM_PROCESS = -502
} maelys_result_t;

const char *maelys_result_str(maelys_result_t r);
int maelys_result_is_retryable(maelys_result_t r);

#ifdef __cplusplus
}
#endif

#endif
